### ISSUE TITLE
Slow response to menu button press.

### ISSUE THREAD

**Issue by amcnulty** [amcnulty/Brew-App#2]
Issue: Slow response time when the user presses the on screen menu button on Motorola Droid 4.

Steps to recreate:
1. Install app on my phone and launch the app.
2. Press the on screen menu button in the top right.

The menu pops up but after a delay time of about a second sometime more. This problem doesn't happen on the emulator in chrome.

Theories:
1. The phone I'm using isn't very good at reading HTML CSS and JS.
2. Too many methods get called when the event fires creating a delay.

**Comment by amcnulty** [comment]
If I wanted to get rid of all the method calls when the menu button is pressed I could condense what is inside of the event listener's function to the following.

``` javascript
if (window.getComputedStyle(optionsMenu).display === "none") optionsMenu.style.display = "block";
else optionsMenu.style.display = "none";
```

**Comment by amcnulty** [comment]
SOLUTION:

The translateZ(0) visually does nothing but will invoke the phone's GPU which isn't standard for a web browser application. In the below code I simply added some transformations of translateZ(0) with the different supported platforms in the same block the CSS translations are.

``` css
.optionsList {
    background: rgba(0, 0, 0, .75);
    position: fixed;
    width: 100%;
    left: 0px;
    top: -200em;
    z-index: 1;
    -webkit-transform: translatez(0);
    -moz-transform: translatez(0);
    -ms-transform: translatez(0);
    -o-transform: translatez(0);
    transform: translatez(0);
    -webkit-transition: top .3s linear;
    -moz-transition: top .3s linear;
    -o-transition: top .3s linear;
    transition: top .3s linear;
}
```

Doing this makes the translation more fluid on a device with a poor CPU like an old phone.
